<?php
$captionarray = array(
'',
'',
'',
'Ginette Sylvain on her wedding day December 2002.',
'Ginette Sylvain at Champs de Mars next to a tap tap.',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'From the Balcony of Detente Tropical Hotel in La Plaine, Haiti',
'Killing a pig',
'Killing a pig',
'Killing a pig',
'A friend of the Sylvain Family from La Plain, Haiti.',
'The busy streets of Port-au-Prince on a Saturday afternoon in 2003.',
'The busy streets of Port-au-Prince on a Saturday afternoon in 2003.',
'The busy streets of Port-au-Prince on a Saturday afternoon in 2003.',
'The busy streets of Port-au-Prince on a Saturday afternoon in 2003.',
'The busy streets of Port-au-Prince on a Saturday afternoon in 2003.',
'The busy streets of Port-au-Prince on a Saturday afternoon in 2003.',
);

?>