<?php
$alttagsarray = array(
'Pre Earthquake Haiti Photos:Ginette Sylvain at Champs de Mars waiting next to a tap tap.',
'Pre Earthquake Haiti Photos:A gospel choir sings at Champs de Mars. There were several other bands performing that night.',
'Pre Earthquake Haiti Photos:A man playing an accoustic guitar, solo, draws a crowd.',
'Pre Earthquake Haiti Photos:The presidential palace decorated for Christmas in December, 2002.',
'Pre Earthquake Haiti Photos:Djouvensong Sylvain preparing to drive me to the airport.',
'Pre Earthquake Haiti Photos:Beautiful photo of Ginette Sylvain in her youth.',
'Pre Earthquake Haiti Photos:Beautiful photo of Ginette Sylvain in her youth, close-up.',
'Pre Earthquake Haiti Photos:Ginette Sylvain on her wedding night.',
'Pre Earthquake Haiti Photos:Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Pre Earthquake Haiti Photos:Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Pre Earthquake Haiti Photos:Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Pre Earthquake Haiti Photos:Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Pre Earthquake Haiti Photos:Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Pre Earthquake Haiti Photos:Leaving the church, going to catch a tap-tap ride back to Detente Tropicale Hotel.',
'Pre Earthquake Haiti Photos:Ginette on the Balcony of Detente Tropical Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette and her then husband at Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Village life in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:On the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette has the calluses on her feet shaved off on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Buying morning bread in La Plaine, Haiti. Bread vendors in the village travel from street to street and house to house.',
'Pre Earthquake Haiti Photos:Buying morning bread in La Plaine, Haiti. Bread vendors in the village travel from street to street and house to house.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:This young boy in La Plaine, Haiti was deaf and could not speak. He was always happy. Saw him several times and was always smiling.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:The children of La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette Sylvain poses on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginette Sylvain poses on the balcony of the Detente Tropicale Hotel in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Ginettes brother Djouvensong, poses for the camera (2003).',
'Pre Earthquake Haiti Photos:Djouvensongs car in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Boss works on Djouvensongs car in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Boss speaks with Ginettes late father.',
'Pre Earthquake Haiti Photos:Boss works on Djouvensongs car in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Boss works on Djouvensongs car in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Boss works on Djouvensongs car in La Plaine, Haiti.',
'Pre Earthquake Haiti Photos:Boss works on Djouvensongs car in La Plaine, Haiti.',
'Djouvensongs daughter, Djouverlie.',
);

?>